language: node_js
sudo: false
node_js: 
  - "8"
cache:
  directories:
    - node_modules
before_install:
  - npm i -g npm@5.6.0
install:
  - npm ci
stages:
  - name: functional-test
  - name: deploy
    if: branch = master
jobs:
  include:
    - stage: functional-test
      script: ./ci/functional-test
    - stage: deploy 
      script: ./ci/deploy
      deploy: &heroku
        provider: heroku
        skip_cleanup: true
        app: $HEROKU_APP_NAME
        api_key:
          secure: "$HEROKU_KEY"