language: node_js
sudo: false
node_js: 
  - "node"
cache:
  directories:
    - ~/.npm
    - ~/.cache
    - ./dist
stages:
  - name: prepare cache
  - name: functional-test
  - name: build
  - name: deploy
jobs:
  include:
    - stage: prepare cache
      script: npm ci
    - stage: functional-test
      script: bash ./ci/functional-test
    - stage: build
      script: bash ./ci/build
    - stage: deploy
      script: bash ./ci/deploy
      env:
        - NPM_CONFIG_PRODUCTION=true
      deploy: &heroku
        provider: heroku
        skip_cleanup: true
        app: $HEROKU_APP_NAME
        api_key:
          secure: "$HEROKU_KEY"
        on:
          branches:
            - master
   